version: '3.8'
services:
  rabbit:
    container_name: rabbit
    image: 'rabbitmq:3-management'
    restart: unless-stopped
    logging:
      driver: none
    network_mode: host
  redis:
    container_name: redis
    image: 'redis:latest'
    restart: unless-stopped
    logging:
      driver: none
    network_mode: host